int menu();
void gotoxy(const HANDLE hout, const int X, const int Y);
void printPattern(int apointer, int bpointer, int cpointer, int n, HANDLE hout, int cmd);
void choose(int cmd);
void hanoi(int cmd, int n, char src, char tmp, char dst, int delay, HANDLE hout);
void choice(int cmd, int n, char src, char tmp, char dst);
void print(int cmd, int n, char src, char dst, int delay, HANDLE hout);
void cls(const HANDLE hout);
void printtower(HANDLE hout);
void printplate(HANDLE hout, int n, char s1, char s2);
void moveplate(int cmd, HANDLE hout, int n, char s1, char s2, int delay);
int getstartx(char s1);
int getstarty(char s1);
int getfinalx(char s3, char s1);
int getfinaly(char s3);
void moveup(int x, int y, char s1, int delay);
void hellmove(int x, int x1, char s1, int delay);
void movedown(int x1, int y1, char s1, char s2, int delay);
void movesleep(int delay);
void playmode(HANDLE hout, int delay, int n, char dst);
